export const ADD_MOVIE_TO_WATCHLIST="ADD_MOVIE_TO_WATCHLIST";
export const REMOVE_MOVIE_FROM_WATCHLIST="REMOVE_MOVIE_FROM_WATCHLIST";
export const ADD_MOVIE_TO_WATCHED="ADD_MOVIE_TO_WATCED";
export const REMOVE_MOVIE_From_WATCHED="REMOVE_MOVIE_From_WATCHED";
export const MOVE_TO_WATCHLIST="MOVE_TO_WATCHLIST";